version: '3'
services:
  app:
    hostname: ruby_sample
    container_name: ruby_sample
    build:
      context: .
    environment:
      RAILS_ENV: development
    tty: true
    stdin_open: true
    ports:
      - '3001:3000'
    volumes:
      - dein_cache:/root/.cache
      - ./:/usr/src/app
    depends_on:
      - db
  db:
    hostname: ruby_sample_db
    container_name: ruby_sample_db
    image: postgres:10.4
    volumes:
      - ruby_sample_db:/var/lib/postgresql/data
volumes:
  dein_cache:
    external: true
  ruby_sample_db:
    external: true
